name: Release Please

on:
  push:
    branches:
      - main

# Prevent concurrent releases
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Release Please
      uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
      id: release
      with:
        config-file: .release-please-config.json
        manifest-file: .release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # Output release information for debugging
    - name: Output release information
      if: ${{ steps.release.outputs.release_created }}
      run: |
        echo "Release created!"
        echo "Tag: ${{ steps.release.outputs.tag_name }}"
        echo "Version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
        echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
        echo ""
        echo "The release tag has been created. The release.yml workflow will handle publishing to npm."