name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Release Please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        config-file: .release-please-config.json
        manifest-file: .release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # Publish to npm when a release is created
    - name: Checkout code
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      if: ${{ steps.release.outputs.release_created }}
      run: npm ci
      
    - name: Build project
      if: ${{ steps.release.outputs.release_created }}
      run: npm run build
      
    - name: Publish to npm
      if: ${{ steps.release.outputs.release_created }}
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Comment on release
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/github-script@v7
      with:
        script: |
          const releaseUrl = `https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}`;
          const npmUrl = `https://www.npmjs.com/package/@neublink/gitplus/v/${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}`;
          
          const comment = `🚀 **Release ${{ steps.release.outputs.tag_name }} Published!**
          
          📦 **NPM Package**: ${npmUrl}
          📋 **Release Notes**: ${releaseUrl}
          
          ### Installation
          \`\`\`bash
          # Install as MCP server in Claude Code
          claude mcp add gitplus -- npx @neublink/gitplus@${{ steps.release.outputs.tag_name }}
          
          # Or install CLI globally
          npm install -g @neublink/gitplus@${{ steps.release.outputs.tag_name }}
          \`\`\``;
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: comment
          });