name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full validation
      run: npm run validate
      
    - name: Build project
      run: npm run build

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog from commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" $LAST_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" --max-count=10)
        fi
        
        # Create changelog file
        cat > CHANGELOG.md << EOF
        # Release v$VERSION
        
        ## Changes
        $CHANGELOG
        
        ## Installation
        \`\`\`bash
        # Install as MCP server in Claude Code
        claude mcp add gitplus -- npx @gitplus/mcp@$VERSION
        
        # Or install CLI globally
        npm install -g @gitplus/mcp@$VERSION
        \`\`\`
        
        ## Full Changelog
        https://github.com/neublink/gitplus/compare/$LAST_TAG...v$VERSION
        EOF
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.changelog.outputs.version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false

  test-published-package:
    needs: [publish-npm, create-github-release]
    runs-on: ubuntu-latest
    steps:
    - name: Wait for NPM propagation
      run: sleep 60
      
    - name: Test NPM installation
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Test global CLI installation
        npm install -g @gitplus/mcp@$VERSION
        
        # Test CLI commands
        gitplus --version
        gitplus --help
        
        # Test in a git repository
        mkdir test-repo && cd test-repo
        git init
        git config user.name "Test User"
        git config user.email "test@example.com"
        
        echo "# Test" > README.md
        git add README.md
        
        # Test gitplus commands (without AI since Claude CLI won't be available)
        gitplus status || echo "Status command tested"
        gitplus validate || echo "Validate command tested"
        
        echo "✅ Package installation and basic functionality verified"